feat: prettier promt, installation, config installation
ongov/ontario-frontend pull request #11
Opened 2024-03-05 15:22 UTC by syed-ods

### Acceptance Criteria and Response
- When setting up a new project via the interactive CLI script, users are prompted to specify if they want to use Prettier in their project
- The default response for the Prettier prompt is “No”

- [x] - Users are inquired to install Prettier
- [x] - The answer defaults to **no**

- When a user opts to add Prettier to their project, the most current stable version of Prettier is added as a project dependency
- When a user opts to add Prettier to their project, prettier and prettier-config-ontario-frontend are installed during the project setup process alongside other project dependencies
- When a user opts to add Prettier to their project, prettier-config-ontario-frontend is added as a project dependency

If the user chooses to install Prettier:
- [x] - the prettier script is added `npm run format` = `"npx prettier --write ."`
- [x] - the `prettier` dependency is added
- [x] - the `prettier-config-ontario-frontend` dependency is also added

- When a user opts to add Prettier to their project, a prettier.config.js file is added to the project and extends the prettier-config-ontario-frontend configuration
- When a user opts to add Prettier to their project, a .prettierignore is added to the project with the default configuration

If the user chooses to install Prettier:
- [x] - a `.prettierignore` file is created,
- [x] - a `prettier.config.js` file is created,
- [x] - the file has **extended** and custom config in addition to our strict preset config

2024-03-06 14:34 UTC, matt-stjean requested changes
This looks good, solid work, just needs some changes to polish it up a bit.

2024-03-06 14:34 UTC, matt-stjean commented on packages/ontario-frontend-cli/create/templates/prettierignore.njk
This doesn't need to be a nunjucks template, it can be a file - there are no values being injected.

2024-03-06 14:34 UTC, matt-stjean commented on packages/ontario-frontend-cli/create/templates/prettier.config.njk
This one can also be a file and not a nunjucks template as nothing is being injected  or computed.

These files will be reused by the "manage" command and they won't be unique to the "create" command. I would recommend creating a directory: `ontario-frontend-cli/shared/prettier`  or something else along those lines. You could still make it specific to create, and as part of the manage work it could be moved too but that is tech debt.

2024-03-06 14:34 UTC, matt-stjean commented on packages/ontario-frontend-cli/create/templates/eslintrc.njk
> +module.exports = {
good catch and fix

2024-03-06 14:34 UTC, matt-stjean commented on packages/ontario-frontend-cli/create/questions.js
> +    name: 'esLint',
🥇

2024-03-06 14:34 UTC, matt-stjean commented on packages/ontario-frontend-cli/create/questions.js
> +    message: 'Want to add Prettier for code formatting?',
I missed this wording in the other PR somehow, the change slipped past me. 

Can we make these messages more formal:
`Add and configure ESLint for finding and fixing code problems?`
`Add and configure Prettier for opinionated code formatting?`

2024-03-06 14:34 UTC, matt-stjean commented on packages/ontario-frontend-cli/create/create.js
> +    prettier: answers.prettier,
Can we make these boolean variables more clearly boolean?  Like `addESLint`, `addPrettier`?

2024-03-06 14:34 UTC, matt-stjean commented on packages/ontario-frontend-cli/create/templates/eslintrc.njk
I did not catch this in the last PR, I wasn't thinking about it. This doesn't need to be a nunjucks template, like the prettier files.

2024-03-07 13:58 UTC, syed-ods commented on packages/ontario-frontend-cli/create/templates/prettier.config.njk
@matt-stjean Is it okay if I create a `shared.js` file to manage/copy the prettier and eslint files based on user input? Similar to `create.js` but within the `ontario-frontend-cli/shared` directory?

2024-03-08 03:17 UTC, matt-stjean approved these changes
It looks good to me, we've both tested it pretty thoroughly

2024-03-08 03:17 UTC, merged