[ONFRONT-79] local add package
ongov/ontario-frontend pull request #38
Opened 2024-06-20 15:08 UTC by matt-stjean

2024-06-21 17:45 UTC, syed-ods reviewed
Correction:
- The command `ontario-add-package eslint --local`, adds only ESLint and not the associated eslint-config package.
- The command `ontario-add-package prettier --local`, adds only Prettier and not the associated prettier-config package. 
- The command `ontario-remove-package <package-name> --local` works fine for both ESLint and Prettier. It also works fine without the `--local` flag. 

I also tried removing the core `ontario-frontend` npm package and install the local copy using `ontario-add-package ontario-frontend --local`, however I got the following error:
`error: command-argument value 'ontario-frontend' is invalid for argument 'package'. Allowed choices are eslint, prettier.`

I'm assuming the command is designed for the local ESLint and Prettier packages only.

2024-06-21 19:22 UTC, kyle-binger-3 requested changes

2024-06-21 19:22 UTC, kyle-binger-3 commented on packages/ontario-frontend-cli/core/utils/project/packageUtils.js
>        // File does not exist, no action needed
Add the `noWarning` param to the JSDoc comment, it's unclear to me why it's needed, e.g. why would we want to suppress the warning?

2024-06-21 19:22 UTC, kyle-binger-3 commented on packages/eslint-config-ontario-frontend/package.json
> -  },
Out of scope but necessary, maybe just a quick note in the PR request / commit about this.

2024-06-21 19:22 UTC, kyle-binger-3 commented on packages/ontario-frontend-cli/core/operations/npm/install.js
> +    PackageInstallationError,
Does this need it's own error? e.g. `PackageLinkError`

2024-06-22 01:52 UTC, matt-stjean commented
I have been spinning on the solution. Getting this to consistently work, covering edge cases, has been more effort than anticipated. This started as a way to save a bit of effort manually linking. 

Putting this in draft for the time being. 
@syed-ods @kyle-binger-3

2024-09-06 14:55 UTC, closed without merging